name: Checks

on:
  push:
    branches: [main, dev]
    paths:
      - '**.js'
      - '**.ts'
      - '**.cjs'
      - 'yarn.lock'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [main, dev]
    paths:
      - '**.js'
      - '**.ts'
      - '**.cjs'
      - 'yarn.lock'
      - '.github/workflows/ci.yml'

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script: [lint, tsc, test, build]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: ${{ matrix.script }}
        run: yarn ${{ matrix.script }}
